apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\anxpp\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sat, 04 Jun 2022 22:25:20 CST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://127.0.0.1:3437
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 04 Jun 2022 22:25:20 CST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\anxpp\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\anxpp\.minikube\profiles\minikube\client.key
